/**
 * Content guardrail — verifies topics against NotebookLM before auto-approval.
 *
 * Flow:
 * 1. Topic is generated by Claude
 * 2. If persona has content_guardrail = 'notebooklm', query NotebookLM
 * 3. If NotebookLM has source material → source_verified = true
 * 4. If NotebookLM does NOT → requires_review = true, review_reason set
 *
 * The NotebookLM query runs via the CLI skill scripts (Python subprocess).
 */

import { execFileSync } from 'child_process';
import path from 'path';

const NOTEBOOKLM_SKILL_DIR = path.join(
    process.env.USERPROFILE || 'C:\\Users\\redle.SOULAAN',
    '.claude', 'skills', 'notebooklm',
);

interface GuardrailResult {
    verified: boolean;
    requiresReview: boolean;
    reviewReason: string | null;
    notebookResponse: string | null;
}

/**
 * Query NotebookLM to verify a topic has source material in the specified notebooks.
 */
export async function verifyTopicAgainstNotebookLM(
    topicTitle: string,
    topicSummary: string,
    notebookIds: string[],
): Promise<GuardrailResult> {
    if (!notebookIds || notebookIds.length === 0) {
        return {
            verified: false,
            requiresReview: true,
            reviewReason: 'No guardrail notebook IDs configured for this persona',
            notebookResponse: null,
        };
    }

    const question = `Does this notebook contain source material about the following topic? Answer YES or NO first, then briefly explain what sources are available. Topic: "${topicTitle}" — ${topicSummary}`;

    for (const notebookId of notebookIds) {
        try {
            const runScript = path.join(NOTEBOOKLM_SKILL_DIR, 'scripts', 'run.py');
            const output = execFileSync('python', [
                runScript,
                'ask_question.py',
                '--question', question,
                '--notebook-id', notebookId,
            ], {
                timeout: 120000,
                encoding: 'utf-8',
                cwd: NOTEBOOKLM_SKILL_DIR,
                env: { ...process.env, PYTHONIOENCODING: 'utf-8' },
            });

            // Check if the response indicates the topic is sourced
            const lowerOutput = output.toLowerCase();
            const hasSource = lowerOutput.includes('yes') &&
                !lowerOutput.includes('no relevant') &&
                !lowerOutput.includes('not covered') &&
                !lowerOutput.includes('no sources') &&
                !lowerOutput.includes('does not contain');

            if (hasSource) {
                return {
                    verified: true,
                    requiresReview: false,
                    reviewReason: null,
                    notebookResponse: output.slice(0, 500),
                };
            }
        } catch (error) {
            console.error(`NotebookLM query failed for notebook ${notebookId}:`, error);
            // On failure, require review rather than blocking
        }
    }

    // If no notebook confirmed the topic
    return {
        verified: false,
        requiresReview: true,
        reviewReason: `Topic "${topicTitle}" not found in NotebookLM source material. Requires Adam review before publishing.`,
        notebookResponse: null,
    };
}

/**
 * Check if a persona requires guardrail verification.
 */
export function hasGuardrail(persona: {
    content_guardrail?: string | null;
    guardrail_notebook_ids?: string[] | null;
}): boolean {
    return persona.content_guardrail === 'notebooklm' &&
        Array.isArray(persona.guardrail_notebook_ids) &&
        persona.guardrail_notebook_ids.length > 0;
}
