-- Migration 024: reference packs — competitor-derived style briefs
-- Filed 2026-07-24. NOT YET APPLIED — this file is version-control only until
-- Adam approves; apply via Supabase MCP / dashboard SQL. Do NOT run through
-- src/scripts/run-migration.ts (broken semicolon splitter).
--
-- One row per ingested competitor video (provenance), plus a distilled
-- personas.style_brief consumed by the prompt builders. NULL style_brief =
-- feature off for a persona; every prompt stays byte-identical (see
-- docs/SPEC-reference-packs.md §2). Both are written ONLY by the local
-- src/scripts/build-reference-pack.ts (service role) — never by crons.

create table if not exists public.reference_packs (
  id uuid primary key default gen_random_uuid(),
  persona_id uuid not null references public.personas(id) on delete cascade,
  source_video_id text not null,
  source_channel text,
  source_url text not null,
  title text not null,
  view_count bigint,
  duration_seconds integer,
  transcript_excerpt text,
  thumbnail_url text,
  thumbnail_style_notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (persona_id, source_video_id)
);

comment on table public.reference_packs is
  'Provenance for competitor-derived style briefs: one row per ingested competitor YouTube video. Distilled into personas.style_brief by src/scripts/build-reference-pack.ts. Service-role only in practice.';

comment on column public.reference_packs.source_video_id is
  'YouTube video id. Unique per persona so re-runs upsert instead of duplicating.';

comment on column public.reference_packs.transcript_excerpt is
  'First ~4000 chars of the cleaned auto-sub transcript. Distillation input only — never surfaced in generated content.';

comment on column public.reference_packs.thumbnail_url is
  'ORIGINAL i.ytimg.com URL. We reference, never re-host, competitor thumbnails (copyright — see SPEC §7).';

comment on column public.reference_packs.thumbnail_style_notes is
  'Claude vision description of the thumbnail''s composition (layout, text treatment, color strategy, emotion, focal object).';

create index if not exists idx_reference_packs_persona
  on public.reference_packs(persona_id);

alter table public.reference_packs enable row level security;

-- Per CLAUDE.md: single-operator system, authenticated users have full access.
-- The ingest script uses the service role and bypasses RLS anyway.
create policy "reference_packs_authenticated_all"
  on public.reference_packs
  for all
  to authenticated
  using (true)
  with check (true);

alter table public.personas add column if not exists style_brief text;

comment on column public.personas.style_brief is
  'Distilled competitor style brief injected into topic/content prompts. NULL = feature off for this persona. Regenerated by src/scripts/build-reference-pack.ts. Max ~1500 chars enforced at ingest.';
